import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { formatBookingDateTime, localDateTimeToIso, BOOKING_STATUSES, BOOKING_TYPES } from "../src/utils/providerBooking.js";

const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("Provider Booking routes use the existing ProviderProtectedRoute",async()=>{const routes=await read("src/routes/AppRoutes.jsx");assert.match(routes,/path="\/provider\/bookings"[\s\S]*ProviderProtectedRoute/);assert.match(routes,/path="\/provider\/bookings\/:id"[\s\S]*ProviderProtectedRoute/);});
test("Provider sidebar exposes Bookings separately from Enquiries",async()=>{const source=await read("src/components/provider/ProviderSidebar.jsx");assert.match(source,/label: "Bookings", to: "\/provider\/bookings"/);assert.match(source,/label: "Enquiries", to: "\/provider\/enquiries"/);});
test("provider Booking service uses central authenticated API without deletion",async()=>{const source=await read("src/services/providerBookingService.js");for(const marker of ["/api/providers/bookings","/summary","/status","apiRequest","token"])assert.match(source,new RegExp(marker.replaceAll("/","\\/")));assert.doesNotMatch(source,/method: "DELETE"/);});
test("Booking inbox has summaries, URL filters, paging, and operational states",async()=>{const source=await read("src/pages/provider/ProviderBookings.jsx");for(const marker of ["useSearchParams","requested","confirmed","upcomingConfirmed","bookingType","targetType","dateFrom","dateTo","search","page","No booking requests yet.","No bookings match these filters.","Try again"])assert.match(source,new RegExp(marker.replaceAll(".","\\.")));assert.match(source,/next\.set\("page","1"\)/);assert.doesNotMatch(source,/fake|demo booking/i);});
test("Booking detail renders snapshots, timezone, contacts, history, and every lifecycle action",async()=>{const source=await read("src/pages/provider/ProviderBookingDetail.jsx");for(const marker of ["mailto:","tel:","Historical Listing","Historical Service","Status History","Confirm Booking","Reject Booking","Mark Completed","Cancel Confirmed Booking","No lifecycle actions","Reason for rejection","Reason for cancellation","does not represent independent slot verification"])assert.match(source,new RegExp(marker));});
test("timezone formatting uses the stored IANA timezone and safely falls back",()=>{const instant="2026-10-10T05:00:00.000Z";const india=formatBookingDateTime(instant,"Asia/Kolkata");assert.equal(india.timezone,"Asia/Kolkata");assert.match(india.time,/10:30/);const invalid=formatBookingDateTime(instant,"Invalid/Zone");assert.equal(invalid.validTimezone,false);assert.match(invalid.timezone,/shown in UTC/);assert.match(localDateTimeToIso("2026-10-10T10:30"),/Z$/);});
test("frontend labels cover the backend lifecycle and compatibility matrix",()=>{assert.deepEqual(BOOKING_STATUSES,["requested","confirmed","rejected","cancelled","completed"]);assert.deepEqual(BOOKING_TYPES,["visit","trial","class","membership","session","consultation"]);});
test("Provider Dashboard keeps Enquiries and adds backend-derived Booking operations",async()=>{const source=await read("src/pages/provider/ProviderDashboard.jsx");assert.match(source,/getProviderEnquirySummary/);assert.match(source,/getProviderBookingSummary/);assert.match(source,/bookingSummary\.requested/);assert.match(source,/bookingSummary\.upcomingConfirmed/);assert.match(source,/to="\/provider\/bookings"/);assert.match(source,/to="\/provider\/enquiries"/);});
