import { useEffect, useMemo, useState } from "react";
import { removeGymCover, removeGymGalleryImage, reorderGymGallery, updateGymGalleryMetadata, uploadGymCover, uploadGymGalleryImage } from "../../services/adminService";
import { buildGalleryMetadataPayload, buildGalleryOrderPayload, GYM_GALLERY_MAX_ITEMS, moveGalleryItem, normalizeAdminGymMedia, validateGymMediaFile } from "../../utils/adminGymMedia";
import DashboardSection from "./dashboard/DashboardSection";
import styles from "../../pages/admin/AdminListingDetail.module.css";

export default function AdminGymMedia({ gymId, images, onUpdated }) {
  const media = useMemo(() => normalizeAdminGymMedia(images), [images]);
  const [coverFile, setCoverFile] = useState(null); const [galleryFile, setGalleryFile] = useState(null);
  const [coverPreview, setCoverPreview] = useState(""); const [galleryPreview, setGalleryPreview] = useState("");
  const [galleryMeta, setGalleryMeta] = useState({ alt: "", category: "gym" }); const [editing, setEditing] = useState({});
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [brokenCoverUrl, setBrokenCoverUrl] = useState("");
  useEffect(() => () => { if (coverPreview) URL.revokeObjectURL(coverPreview); if (galleryPreview) URL.revokeObjectURL(galleryPreview); }, [coverPreview, galleryPreview]);
  const choose = (kind, file) => { const validation = validateGymMediaFile(file); setError(validation); if (validation) return; const url = URL.createObjectURL(file); if (kind === "cover") { if (coverPreview) URL.revokeObjectURL(coverPreview); setCoverFile(file); setCoverPreview(url); } else { if (galleryPreview) URL.revokeObjectURL(galleryPreview); setGalleryFile(file); setGalleryPreview(url); } };
  const complete = (updated) => { onUpdated(updated); setError(""); };
  const run = async (key, action) => { if (busy) return; setBusy(key); setError(""); try { complete(await action()); } catch (err) { setError(err.message || "Media operation failed."); } finally { setBusy(""); } };
  const clearCoverSelection = () => { if (coverPreview) URL.revokeObjectURL(coverPreview); setCoverFile(null); setCoverPreview(""); };
  const clearGallerySelection = () => { if (galleryPreview) URL.revokeObjectURL(galleryPreview); setGalleryFile(null); setGalleryPreview(""); setGalleryMeta({ alt: "", category: "gym" }); };
  const reorder = (index, direction) => { const next = moveGalleryItem(media.gallery, index, direction); if (next === media.gallery) return; run("order", async () => reorderGymGallery(gymId, buildGalleryOrderPayload(next))); };
  return <DashboardSection title="Media">
    {error && <p className={styles.mediaError} role="alert">{error}</p>}
    <div className={styles.mediaBlock}><div><h3 className={styles.mediaTitle}>Cover</h3><p className={styles.helperText}>Landscape hero image · JPEG, PNG or WebP · maximum 4 MB</p></div>
      <div className={styles.coverPreview}>{(coverPreview || (media.cover && media.cover !== brokenCoverUrl)) ? <img src={coverPreview || media.cover} alt="Gym cover" onError={() => !coverPreview && setBrokenCoverUrl(media.cover)} /> : <span>No cover image</span>}</div>
      <div className={styles.mediaActions}><label className={styles.fileBtn}>{media.cover ? "Change Cover" : "Upload Cover"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => choose("cover", event.target.files?.[0])} disabled={Boolean(busy)} /></label>{coverFile && <><span className={styles.fileName}>{coverFile.name}</span><button type="button" className={styles.editBtn} onClick={() => run("cover", async () => { const updated = await uploadGymCover(gymId, coverFile); clearCoverSelection(); return updated; })} disabled={Boolean(busy)}>{busy === "cover" ? "Uploading…" : "Upload"}</button><button type="button" className={styles.secondaryBtn} onClick={clearCoverSelection} disabled={Boolean(busy)}>Cancel</button></>}{media.cover && <button type="button" className={styles.dangerBtn} disabled={Boolean(busy)} onClick={() => window.confirm("Remove this cover image?") && run("remove-cover", () => removeGymCover(gymId))}>Remove Cover</button>}<span className={styles.mediaStatus}>{media.cover ? media.coverManaged ? "Managed" : "Legacy / unmanaged" : ""}</span></div>
    </div>
    <div className={styles.mediaBlock}><div><h3 className={styles.mediaTitle}>Gallery</h3><p className={styles.helperText}>{media.gallery.length} of {GYM_GALLERY_MAX_ITEMS} images</p></div>
      {galleryPreview && <div className={styles.galleryUploadPreview}><img src={galleryPreview} alt="Selected gallery preview" /><input value={galleryMeta.alt} placeholder="Alt text" onChange={(event) => setGalleryMeta((current) => ({ ...current, alt: event.target.value }))} /><input value={galleryMeta.category} placeholder="Category" onChange={(event) => setGalleryMeta((current) => ({ ...current, category: event.target.value }))} /><span className={styles.fileName}>{galleryFile?.name}</span><button type="button" className={styles.editBtn} disabled={Boolean(busy)} onClick={() => run("gallery-upload", async () => { const updated = await uploadGymGalleryImage(gymId, galleryFile, galleryMeta); clearGallerySelection(); return updated; })}>{busy === "gallery-upload" ? "Uploading…" : "Add Image"}</button><button type="button" className={styles.secondaryBtn} onClick={clearGallerySelection} disabled={Boolean(busy)}>Cancel</button></div>}
      {!galleryPreview && media.gallery.length < GYM_GALLERY_MAX_ITEMS && <label className={styles.fileBtn}>Add Gallery Image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => choose("gallery", event.target.files?.[0])} disabled={Boolean(busy)} /></label>}
      <div className={styles.galleryGrid}>{media.gallery.map((item, index) => { const values = editing[item.id] || { alt: item.alt, category: item.category }; return <article className={styles.galleryCard} key={item.id}><div className={styles.galleryImage}>{item.url ? <img src={item.url} alt={item.alt || "Gym gallery"} /> : <span>Image unavailable</span>}</div><span className={styles.mediaStatus}>{item.managed ? "Managed" : "Legacy / unmanaged"}</span><input aria-label="Gallery alt text" value={values.alt} onChange={(event) => setEditing((current) => ({ ...current, [item.id]: { ...values, alt: event.target.value } }))} /><input aria-label="Gallery category" value={values.category} onChange={(event) => setEditing((current) => ({ ...current, [item.id]: { ...values, category: event.target.value } }))} /><div className={styles.galleryActions}><button type="button" onClick={() => run(`meta-${item.id}`, () => updateGymGalleryMetadata(gymId, item.id, buildGalleryMetadataPayload(values)))} disabled={Boolean(busy)}>Save</button><button type="button" onClick={() => reorder(index, -1)} disabled={Boolean(busy) || index === 0}>↑</button><button type="button" onClick={() => reorder(index, 1)} disabled={Boolean(busy) || index === media.gallery.length - 1}>↓</button><button type="button" className={styles.dangerBtn} onClick={() => window.confirm("Remove this gallery image?") && run(`remove-${item.id}`, () => removeGymGalleryImage(gymId, item.id))} disabled={Boolean(busy)}>Remove</button></div></article>; })}</div>
    </div>
  </DashboardSection>;
}
