import { useCallback, useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import ProviderLayout from "../../layouts/ProviderLayout";
import StatusBadge from "../../components/provider/StatusBadge";
import { useProviderAuth } from "../../context/ProviderAuthContext";
import { getProviderBookings, getProviderBookingSummary } from "../../services/providerBookingService";
import { BOOKING_STATUSES, BOOKING_STATUS_LABELS, BOOKING_STATUS_TONES, BOOKING_TARGET_TYPES, BOOKING_TYPES, formatBookingDateTime, isoToLocalDateTime, localDateTimeToIso } from "../../utils/providerBooking";
import styles from "./ProviderBookings.module.css";

export default function ProviderBookings() {
  const { token } = useProviderAuth(); const [params,setParams]=useSearchParams(); const page=Math.max(1,Number(params.get("page"))||1); const status=params.get("status")||""; const bookingType=params.get("bookingType")||""; const targetType=params.get("targetType")||""; const search=params.get("search")||""; const dateFrom=params.get("dateFrom")||""; const dateTo=params.get("dateTo")||"";
  const [draftSearch,setDraftSearch]=useState(search); const [items,setItems]=useState([]); const [pagination,setPagination]=useState(null); const [summary,setSummary]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const[list,counts]=await Promise.all([getProviderBookings(token,{page,limit:20,status,bookingType,targetType,search,dateFrom,dateTo}),getProviderBookingSummary(token)]);setItems(list.bookings);setPagination(list.pagination);setSummary(counts);}catch(err){setError(err.message||"Failed to load bookings.");}finally{setLoading(false);}},[token,page,status,bookingType,targetType,search,dateFrom,dateTo]);
  useEffect(()=>{Promise.resolve().then(load);},[load]); useEffect(()=>{
    // Keep browser back/forward navigation reflected in the controlled input.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setDraftSearch(search);
  },[search]);
  const update=(changes)=>{const next=new URLSearchParams(params);Object.entries(changes).forEach(([key,value])=>value?next.set(key,String(value)):next.delete(key));if(!("page" in changes))next.set("page","1");setParams(next,{replace:true});}; const filtered=Boolean(status||bookingType||targetType||search||dateFrom||dateTo); const clear=()=>{setDraftSearch("");setParams({}, {replace:true});};
  return <ProviderLayout title="Bookings" subtitle="Review and manage customer booking requests."><div className={styles.page}>
    <div className={styles.notice}>Bookings are preferred-time requests. Confirm only after your business has accepted the requested date and time.</div>
    <div className={styles.summary}>{[["Requested",summary?.requested],["Confirmed",summary?.confirmed],["Upcoming",summary?.upcomingConfirmed],["Total",summary?.total]].map(([label,value])=><div key={label}><strong>{loading&&!summary?"…":value||0}</strong><span>{label}</span></div>)}</div>
    <form className={styles.filters} onSubmit={(event)=>{event.preventDefault();update({search:draftSearch.trim()});}}><label className={styles.search}><span>Search bookings</span><div><input aria-label="Search bookings" maxLength={100} value={draftSearch} onChange={(event)=>setDraftSearch(event.target.value)} placeholder="Customer, listing, service or note"/><button>Search</button></div></label><label><span>Status</span><select value={status} onChange={(event)=>update({status:event.target.value})}><option value="">All statuses</option>{BOOKING_STATUSES.map(value=><option value={value} key={value}>{BOOKING_STATUS_LABELS[value]}</option>)}</select></label><label><span>Booking type</span><select value={bookingType} onChange={(event)=>update({bookingType:event.target.value})}><option value="">All booking types</option>{BOOKING_TYPES.map(value=><option value={value} key={value}>{value}</option>)}</select></label><label><span>Target type</span><select value={targetType} onChange={(event)=>update({targetType:event.target.value})}><option value="">All listing types</option>{BOOKING_TARGET_TYPES.map(value=><option value={value} key={value}>{value}</option>)}</select></label><label><span>Preferred from</span><input type="datetime-local" value={isoToLocalDateTime(dateFrom)} onChange={(event)=>update({dateFrom:localDateTimeToIso(event.target.value)})}/></label><label><span>Preferred to</span><input type="datetime-local" value={isoToLocalDateTime(dateTo)} onChange={(event)=>update({dateTo:localDateTimeToIso(event.target.value)})}/></label><button type="button" className={styles.clear} disabled={!filtered} onClick={clear}>Clear filters</button></form>
    {error?<div className={styles.state} role="alert"><h2>Unable to load bookings</h2><p>{error}</p><button onClick={load}>Try again</button></div>:loading&&!items.length?<div className={styles.state} role="status">Loading bookings…</div>:!items.length?<div className={styles.state}><h2>{filtered?"No bookings match these filters.":"No booking requests yet."}</h2>{filtered&&<button onClick={clear}>Clear filters</button>}</div>:<><div className={styles.tableCard}><table><thead><tr><th>Customer</th><th>Listing / Service</th><th>Type</th><th>Preferred date & time</th><th>Status</th><th>Submitted</th><th>Action</th></tr></thead><tbody>{items.map(item=>{const when=formatBookingDateTime(item.scheduledFor,item.timezone);return <tr key={item.id}><td data-label="Customer"><strong>{item.contact.name}</strong><small>{item.contact.email}</small></td><td data-label="Listing / Service"><strong>{item.listing.name}</strong><small>{item.service?.name||"—"}</small></td><td data-label="Booking type"><span className={styles.capitalize}>{item.bookingType}</span></td><td data-label="Preferred time"><strong>{when.date}</strong><small>{when.time} · {when.timezone}</small></td><td data-label="Status"><StatusBadge tone={BOOKING_STATUS_TONES[item.status]} label={BOOKING_STATUS_LABELS[item.status]||item.status}/></td><td data-label="Submitted">{new Date(item.createdAt).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</td><td data-label="Action"><Link className={styles.action} to={`/provider/bookings/${item.id}`}>View booking</Link></td></tr>;})}</tbody></table></div>{pagination?.pages>1&&<nav className={styles.pagination} aria-label="Booking pages"><button disabled={page<=1||loading} onClick={()=>update({page:page-1})}>Previous</button><span>Page {page} of {pagination.pages}</span><button disabled={page>=pagination.pages||loading} onClick={()=>update({page:page+1})}>Next</button></nav>}</>}
  </div></ProviderLayout>;
}
