import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import ProviderLayout from "../../layouts/ProviderLayout";
import StatusBadge from "../../components/provider/StatusBadge";
import { useProviderAuth } from "../../context/ProviderAuthContext";
import { getProviderBooking, updateProviderBookingStatus } from "../../services/providerBookingService";
import { BOOKING_STATUS_LABELS, BOOKING_STATUS_TONES, formatBookingDateTime } from "../../utils/providerBooking";
import styles from "./ProviderBookingDetail.module.css";

function Row({label,children}){return <div><dt>{label}</dt><dd>{children||"—"}</dd></div>;}
function ReasonDialog({ action, onClose, onSubmit, pending, error }) { const [reason,setReason]=useState(""); useEffect(()=>{const close=(event)=>{if(event.key==="Escape"&&!pending)onClose();};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[onClose,pending]); const rejecting=action==="rejected"; return <div className={styles.backdrop} role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!pending)onClose();}}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="reason-title"><h2 id="reason-title">{rejecting?"Reject Booking":"Cancel Confirmed Booking"}</h2><p>{rejecting?"Explain why this request cannot be accepted.":"The customer will see this cancellation reason."}</p><form onSubmit={(event)=>{event.preventDefault();onSubmit(reason);}}><label htmlFor="booking-reason">{rejecting?"Reason for rejection":"Reason for cancellation"}</label><textarea id="booking-reason" autoFocus required maxLength={500} value={reason} onChange={(event)=>setReason(event.target.value)} />{error&&<div className={styles.dialogError} role="alert">{error}</div>}<div className={styles.dialogActions}><button type="button" onClick={onClose} disabled={pending}>Keep Booking</button><button type="submit" className={styles.dangerAction} disabled={pending||!reason.trim()}>{pending?"Updating…":rejecting?"Reject Booking":"Cancel Booking"}</button></div></form></section></div>; }

export default function ProviderBookingDetail(){const{id}=useParams();const{token}=useProviderAuth();const[item,setItem]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[actionPending,setActionPending]=useState(false);const[actionError,setActionError]=useState("");const[reasonAction,setReasonAction]=useState("");
  const [currentTime] = useState(Date.now);
  const load=useCallback(async()=>{setLoading(true);setError("");try{setItem(await getProviderBooking(token,id));}catch(err){setError(err.message||"Failed to load booking.");}finally{setLoading(false);}},[token,id]);useEffect(()=>{Promise.resolve().then(load);},[load]);
  const updateStatus=async(status,reason="")=>{if(actionPending)return;setActionPending(true);setActionError("");try{await updateProviderBookingStatus(token,id,{status,...(reason?{reason}:{})});setReasonAction("");await load();}catch(err){setActionError(err.message||"Unable to update booking status.");}finally{setActionPending(false);}};
  const confirm=()=>{if(window.confirm("Confirming means you are accepting this customer's booking request for the displayed preferred date and time."))updateStatus("confirmed");}; const complete=()=>{if(window.confirm("Mark this booking completed? This records that the scheduled service took place."))updateStatus("completed");};
  const when=item?formatBookingDateTime(item.scheduledFor,item.timezone):null;const scheduledPast=item?new Date(item.scheduledFor).getTime()<=currentTime:false;
  return <ProviderLayout title="Booking Detail" subtitle="Review the request and record the real business outcome."><div className={styles.page}><Link className={styles.back} to="/provider/bookings">← Back to bookings</Link>{error&&!item?<div className={styles.state} role="alert"><h2>Unable to load booking</h2><p>{error}</p><button onClick={load}>Try again</button></div>:loading&&!item?<div className={styles.state} role="status">Loading booking…</div>:item?<>
    {actionError&&!reasonAction&&<div className={styles.inlineError} role="alert">{actionError}</div>}<header className={styles.hero}>{item.listing.image?.url&&<img src={item.listing.image.url} alt={item.listing.image.alt||""}/>}<div><span>{item.listing.entityType?.replaceAll("_"," ")}</span><h2>{item.listing.name}</h2><p>{item.service?.name} · {item.bookingType}</p></div><StatusBadge tone={BOOKING_STATUS_TONES[item.status]} label={BOOKING_STATUS_LABELS[item.status]||item.status}/></header>
    <div className={styles.grid}><section><h3>Booking Summary</h3><dl><Row label="Preferred date">{when.date}</Row><Row label="Preferred time">{when.time}</Row><Row label="Timezone">{when.timezone}</Row><Row label="Booking type"><span className={styles.capitalize}>{item.bookingType}</span></Row><Row label="Submitted">{new Date(item.createdAt).toLocaleString("en-IN")}</Row></dl>{item.status==="requested"&&scheduledPast&&<p className={styles.warning}>This request time has passed. It cannot be confirmed, but it may be rejected with an explanation.</p>}</section>
    <section><h3>Customer</h3><dl><Row label="Name">{item.contact.name}</Row><Row label="Email"><a href={`mailto:${item.contact.email}`}>{item.contact.email}</a></Row><Row label="Phone">{item.contact.phone?<a href={`tel:${item.contact.phone}`}>{item.contact.phone}</a>:"—"}</Row></dl><h4>Customer Note</h4><p className={styles.note}>{item.note||"No note provided."}</p></section>
    <section><h3>Historical Listing</h3><dl><Row label="Name">{item.listing.name}</Row><Row label="Type">{item.listing.entityType?.replaceAll("_"," ")}</Row></dl>{item.currentListing?.providerListingHref?<Link className={styles.link} to={item.currentListing.providerListingHref}>View current listing</Link>:<p className={styles.muted}>{!item.currentListing?.exists?"The current listing no longer exists.":!item.currentListing?.stillOwnedByProvider?"This listing is no longer owned by this provider account.":"The listing is not currently available."}</p>}</section>
    <section><h3>Historical Service</h3><dl><Row label="Service">{item.service?.name}</Row><Row label="Duration">{item.service?.duration}</Row><Row label="Schedule">{[item.service?.schedule,item.service?.time].filter(Boolean).join(" · ")}</Row><Row label="Trainer">{item.service?.trainer}</Row><Row label="Specialty">{item.service?.specialty}</Row><Row label="Display price">{item.service?.displayPrice!=null?`${item.service.currency||""}${item.service.displayPrice}`:"—"}</Row></dl>{item.service?.description&&<p className={styles.note}>{item.service.description}</p>}</section>
    <section className={styles.history}><h3>Status History</h3><ol>{item.statusHistory.map((entry,index)=><li key={`${entry.status}-${entry.changedAt}-${index}`}><span/><div><strong>{BOOKING_STATUS_LABELS[entry.status]||entry.status}</strong><small>{new Date(entry.changedAt).toLocaleString("en-IN")} · {entry.changedByRole}</small>{entry.reason&&<p>{entry.reason}</p>}</div></li>)}</ol>{item.resolution&&<div className={styles.resolution}><strong>{item.resolution.byRole==="provider"?"Provider":"Customer"} resolution</strong><p>{item.resolution.reason||"No reason provided."}</p></div>}</section></div>
    <section className={styles.actions}><div><h3>Booking Actions</h3><p>Actions update the customer-visible lifecycle. A confirmation records business acceptance; it does not represent independent slot verification.</p></div>{item.status==="requested"&&<><button className={styles.primaryAction} disabled={actionPending||scheduledPast} title={scheduledPast?"Past requests cannot be confirmed.":""} onClick={confirm}>Confirm Booking</button><button className={styles.dangerOutline} disabled={actionPending} onClick={()=>{setActionError("");setReasonAction("rejected");}}>Reject</button></>}{item.status==="confirmed"&&<><button className={styles.primaryAction} disabled={actionPending||!scheduledPast} title={!scheduledPast?"Completion is available after the scheduled time.":""} onClick={complete}>Mark Completed</button><button className={styles.dangerOutline} disabled={actionPending} onClick={()=>{setActionError("");setReasonAction("cancelled");}}>Cancel Confirmed Booking</button></>}{["rejected","cancelled","completed"].includes(item.status)&&<span className={styles.muted}>No lifecycle actions are available for this terminal booking.</span>}</section>
    {reasonAction&&<ReasonDialog action={reasonAction} pending={actionPending} error={actionError} onClose={()=>{setReasonAction("");setActionError("");}} onSubmit={(reason)=>updateStatus(reasonAction,reason.trim())}/>} 
  </>:null}</div></ProviderLayout>;
}
